### ISSUE TITLE
配置Alinode报错nodeinstall --install-alinode ^3

### ISSUE THREAD

**Issue by HelloJasonZhang** [cnodejs/egg-cnode#144]
根据下面的文档执行nodeinstall --install-alinode ^3命名报错，不知道是什么原因。
https://helpcdn.aliyun.com/document_detail/60907.html

`ubuntu@VM-0-16-ubuntu:~/code/egg-cnode$ npm i nodeinstall -g^C
ubuntu@VM-0-16-ubuntu:~/code/egg-cnode$ nodeinstall --install-alinode ^3
Error: GET http://alinode.aliyun.com/dist/new-alinode/v3.12.0/alinode-v3.12.0-linux-x86.tar.gz got 404
    at downloadTgz (/usr/lib/node_modules/nodeinstall/lib/installer/installer.js:125:17)
    at downloadTgz.next (<anonymous>)
    at onFulfilled (/usr/lib/node_modules/nodeinstall/node_modules/co/index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
`

**Comment by JacksonTian** [comment]
@hyj1991 看看
